name: pk_servizi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dio: ^5.9.0
  velocity_x: ^4.1.0
  dio_smart_retry: ^7.0.1
  pretty_dio_logger: ^1.4.0
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  json_annotation: ^4.9.0
  google_sign_in: ^6.2.1
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_stripe: ^10.1.1
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/logos/